url: "https://airesearch.in.th"
title: "airesearch.in.th"
timezone: Asia/Bangkok

collections:
  pages:
    output: true
    sort_by: order
    permalink: /:name
  releases:
    output: true
    sort_by: order
    permalink: /:collection/:name
  services:
    output: true
    sort_by: order
    permalink: /:collection/:name
  resources:
    output: true
    sort_by: order
    permalink: /:collection/:name
  sponsors:
    output: true
    sort_by: order
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      navbar_display: true
  - scope:
      path: ""
      type: releases
    values:
      layout: release
      featured: false
  - scope:
      path: ""
      type: services
    values:
      layout: service
      featured: false
  - scope:
      path: ""
      type: resources
    values:
      layout: resource
      featured: false
  - scope:
      path: ""
      type: sponsors
    values:
      featured: false

sass:
  style: compressed

strict_front_matter: true

exclude:
  - ".gitignore"
  - ".jekyll-cache"
  - ".vscode"
  - Gemfile
  - Gemfile.lock
  