title: "airesearch.in.th"
url: "https://airesearch.in.th"
locale: en-US
timezone: Asia/Bangkok
permalink: /blog/:categories/:year/:month/:day/:title/
facebook_page_id: 106755957360414
google_tag_id: UA-141096942-1
seo_keywords:
  - artificial intelligence
  - research
  - vistec
  - depa
  - vidyasirimedhi
  - vidyasirimedhi institute of science and technology
  - digital economy promotion agency
  - machine translation
  - open data
  - dataset
  - model
  - artificial intelligence research
  - research institute

collections:
  pages:
    output: true
    sort_by: order
    permalink: /:name/
  releases:
    output: true
    sort_by: date
    permalink: /:collection/:name/
  services:
    output: true
    sort_by: order
    permalink: /:collection/:name/
  resources:
    output: true
    sort_by: order
    permalink: /:collection/:name/
  supporters:
    output: true
    sort_by: order
    permalink: /:collection/:name/
  crew:
    output: true
    sort_by: order
    permalink: /:collection/:name/

defaults:
  - scope:
      path: 
      type: posts
    values:
      layout: post
  - scope:
      path: 
      type: pages
    values:
      layout: default
      navbar_display: true
  - scope:
      path: 
      type: releases
    values:
      featured: false
      layout: release
  - scope:
      path: 
      type: services
    values:
      featured: false
      layout: service
  - scope:
      path: 
      type: resources
    values:
      featured: false
      layout: resource
  - scope:
      path: 
      type: supporters
    values:
      featured: true
  - scope:
      path: 
      type: crew
    values:
      layout: crew_member

sass:
  style: compressed

strict_front_matter: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: plaintext
    
exclude:
  - ".github"
  - ".gitignore"
  - ".jekyll-cache"
  - ".vscode"
  - Gemfile
  - Gemfile.lock
  - Gemfile.development
  - Gemfile.development.lock
