url: "https://airesearch.in.th" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "airesearch.in.th" # the name of your site, e.g. ACME Corp.
