url: "https://airesearch.in.th" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "airesearch.in.th" # the name of your site, e.g. ACME Corp.

collections:
  pages:
    output: true
    permalink: /:path
  carousel_slides:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      navbar_display: true
