url: "https://airesearch.in.th" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "airesearch.in.th" # the name of your site, e.g. ACME Corp.

collections:
  pages:
    output: true
    sort_by: order
    permalink: /:name
  releases:
    output: true
    sort_by: order
    permalink: /:collection/:name
  services:
    output: true
    sort_by: order
    permalink: /:collection/:name
  # resources:
  #   output: true
  #   sort_by: order
  #   permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      navbar_display: true
  - scope:
      path: ""
      type: releases
    values:
      layout: release
      featured: false
  - scope:
      path: ""
      type: services
    values:
      layout: service
      featured: false
  # - scope:
  #     path: ""
  #     type: resources
  #   values:
  #     layout: resource
  #     featured: false
