name: "Jekyll: Build (latest)"

on: [push, pull_request]

jobs:
  jekyll-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: docker://ruby:2.7-alpine
        with:
          args: bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production
