name: "Jekyll: Build"

on: [push, pull_request]

jobs:
  jekyll-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: gem update --system --no-document
      - run: gem update bundler
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec jekyll build --trace -d build
        env:
          JEKYLL_ENV: production
      - uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: build/
