name: "Jekyll: Build"

on: [push, pull_request]

jobs:
  jekyll-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: build
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --trace
